# --- STAGE 1: Build ---
FROM node:22 AS builder

WORKDIR /usr/src/app

COPY package*.json ./

# Copy source code and build the project
COPY . .

RUN npm ci

RUN npm run build

ENV PORT=8080

EXPOSE 8080

CMD ["node", "dist/server.js"]