name: Deploy Frontend to S3

on:
  push:
    branches:
      - dev
    paths:
      - 'frontend/**' # Only triggers if files in the frontend folder change
      - '.github/workflows/frontend-deploy.yml' # Also run if the workflow itself changes

permissions:
  id-token: write # Required for OIDC.
  contents: read  # Required for checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-1

      - name: Deploy to S3
        # --delete ensures files removed from your repo are also removed from S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront Cache
        # Tells CloudFront to dump the old version and grab the new files from S3
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
            --paths "/*"